language: "perl"

sudo: false

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

git:
  submodules: false

#before_install:
#  - sed -i 's/git@github.com:/http:\/\/github.com\//' .gitmodules
#  - git submodule update --init --recursive
